<a href="https://colab.research.google.com/github/Alinedev85/GYM-PYTHON/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
# Matriz

In [5]:
m = np.array([10,24,54,78,31])
m

array([10, 24, 54, 78, 31])

In [6]:
type(m)

numpy.ndarray

In [7]:
print(m)

[10 24 54 78 31]


In [8]:
print('{}'.format(m[2]))

54


In [14]:
print('{}'.format(m[0:4]))

[10 24 54 78]


In [15]:
m

array([10, 24, 54, 78, 31])

In [17]:
# mostra a quantidade de linhas
print(m.shape)

(5,)


In [18]:
md = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])

In [19]:
print('{}'.format(md))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [20]:
md.T # transpor um array

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [24]:
md[1,1]

8

In [25]:
md[1][1]

8

In [26]:
md.shape[0]
 # o parametro de entrada 0 permite ver a quantidade de linhas do array
 # 0 para linhas  1 para colunas

2

In [27]:
md.shape[1]
 # o parametro de entrada 0 permite ver a quantidade de linhas do array
 # 0 para linhas  1 para colunas

6

In [29]:
# submatriz  recebe as linhas localizadas na posição 0 e 1 e colunas de zeero a 2

subMd = md[0:2, 0:3]
subMd

array([[1, 2, 3],
       [7, 8, 9]])

In [30]:
subMd = md[0:2, 0:3]
print("{}".format(subMd))

[[1 2 3]
 [7 8 9]]


In [31]:
#modificar elemento das matrizes
# tudo que for null receba o numero ou uma letra para depois usar os filtros
md[1][1] = 11
md

array([[ 1,  2,  3,  4,  5,  6],
       [ 7, 11,  9, 10, 11, 12]])

In [35]:
md[1][1] = 0

In [36]:
md


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  0,  9, 10, 11, 12]])

In [38]:
#transformar para numero real
mr =np.array([[1.0,2,3,4,5],[1000,12,32111,788,1],[6,7,8,9,1999]])
mr

array([[1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00, 5.0000e+00],
       [1.0000e+03, 1.2000e+01, 3.2111e+04, 7.8800e+02, 1.0000e+00],
       [6.0000e+00, 7.0000e+00, 8.0000e+00, 9.0000e+00, 1.9990e+03]])

In [39]:
print("{}".format(mr))

[[1.0000e+00 2.0000e+00 3.0000e+00 4.0000e+00 5.0000e+00]
 [1.0000e+03 1.2000e+01 3.2111e+04 7.8800e+02 1.0000e+00]
 [6.0000e+00 7.0000e+00 8.0000e+00 9.0000e+00 1.9990e+03]]
